name: Node CI Workflow

on:
  pull_request:
    branches:
      - main # main 브랜치로의 PR 이벤트 트리거
  push:
    branches:
      - main # main 브랜치에 푸시될 때 트리거

defaults:
  run:
    shell: bash
    working-directory: ./ # ./ 디렉터리에서 실행

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 의존성 설치
      - name: Install Dependencies
        run: npm install

      # 3. 테스트 실행
      - name: Run Tests
        run: npm test
